services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e-commerce-app-rails-db-dev
      MYSQL_USER: rails
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - kafka

  kafka:
    image: apache/kafka:4.0.0
    container_name: ecommerce-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  consumer:
    build: .
    command: bash -c "bundle exec rails runner 'RdkafkaConsumer.new.start'"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
    depends_on:
      - db
      - kafka

  notification_consumer:
    build: .
    command: bash -c "bundle exec rails runner 'NotificationConsumer.new.start'"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
    depends_on:
      - db
      - kafka

volumes:
  mysql_data:
