default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails
  password: password
  host: db
  port: 3306

development:
  <<: *default
  database: e-commerce-app-rails-db-dev

test:
  <<: *default
  database: e-commerce-rails-app-db-test

production:
  <<: *default
  database: e-commerce-rails-app-db-prod
  username: rails
  password: password
  host: db
